users:
  'soaringalano_cx':
      password: '123456'
      privilege: 'admin'
  'soaringalano_zdx':
      password: '123456'
      privilege: 'admin'
  'soaringalano_lm':
      password: '123456'
      privilege: 'admin'
  'admin':
      password: '123456'
      privilege: 'admin'
