version: "3.11"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'huggingface_rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/home/linmao/workspaces/python/soaringalano/cloudserver/.docker-conf/rabbitmq/lib
        - ~/.docker-conf/rabbitmq/log/:/home/linmao/workspaces/python/soaringalano/cloudserver/.docker-conf/rabbitmq/log
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
